### ISSUE TITLE
A MKV file incorrectly named .mp4 is not added

### ISSUE THREAD

**Issue by MrDemocracy** [BrunoReX/jmkvpropedit#10]
I have a folder of mkv files that are incorrectly named with the .mp4 file extension. When I try to add them to jmkvpropedit, nothing happens.

**Comment by chippie** [comment]
Why not just remane them to .mkv??? Sorry but totally confused by your request! If the files are incorrectly named then why not fix them. If named .mp4 to add them to a different program etc. then simply rename to .mkv then back again right!

Have to remember this is a simpte program to change the header information. It will not check or validfate the contents of your container be it .mkv or .mp4 when you load the files, it simply works on the extension.
