### ISSUE TITLE
Option to recode subtitle to UTF-8

### ISSUE THREAD

**Issue by MrDemocracy** [BrunoReX/jmkvpropedit#11]
It would be awesome if your program could recode subtitle to a different unicode character set, preferably UTF-8.
I have hundreds of mkv's with incorrect charsets.
My current way of fixing this is by dragging the mkv file into SubtitleEdit, changing it to UTF-8, saving it as a srt file, before I finally can drag both the mkv and the new srt file into MKVToolNix GUI and remux them (making sure to deselect the old subtitle file). Then I can delete the old MKV with the incorrect subtitle charset and remove the `(1)` from the end of the filename of the new file.
This would take forever to do manually and I have basically just put that project on hold for now.

So it would be fantastic if this could be automated by jmkvpropedit.

**Comment by chippie** [comment]
I am no expert but this can just not be achieved as the charactger set is coded in the subtitle file. That is why you have to remux them. This program simply edits the file header.
