### ISSUE TITLE
'Hieroglyphs' in "Output" tab messages 

### ISSUE THREAD

**Issue by Starroma** [BrunoReX/jmkvpropedit#13]
In the Russian-language Wimdows 7 (x32) messages in the "Output" tab are displayed as 'hieroglyphs'.
![2018-10-12_010128](https://user-images.githubusercontent.com/22007366/46836649-17ff8400-cdbb-11e8-937c-739e8d903a1d.jpg)

**Comment by GLoBoLLo** [comment]
In French too, but just for certain characters that are not present in English (accents, cedillas, etc.). It's much less blatant than in Russian  ;)

**Comment by BrunoReX** [comment]
I think it may be because I was not compiling in UTF-8, should be resolved in the new version I will publish shortly.
