### ISSUE TITLE
Files aren't modified at all if they don't contain every single edit specification

### ISSUE THREAD

**Issue by Jtasiu** [BrunoReX/jmkvpropedit#14]
For example, let's say I load 3 files in jmkvpropedit where the 1st and 2nd have 1 audio track and the 3rd file has 2 audio tracks. I then add new attachments to all files, change video title properties for all files, and change audio track number 2's title property then click Process files. 

The first two will be left unprocessed (because it cannot find audio track number 2) while the 3rd will be properly processed. This results in losing the other attachment and video titles property edits I have done. 

Instead jmkvpropedit should be able to do the edits that it can do (add the attachments and video title properties to the first two files as it is possible) and leave the edits it can't do out (like changing audio track number 2's title change in this case as it can't find a corresponding "a2")

**Comment by chippie** [comment]
Do not necessarily agreee with this. If it works the way you reques then you lose control of what is being modified and when. The way it curretly works allows you to only modify specific files that contain the changes you reuqire.
It is hardly difficult to uckeck the 'Edit this Track' option as you progress through your changes.
