### ISSUE TITLE
Not A Issue: How Do You Compile This In Windows?

### ISSUE THREAD

**Issue by itman2000my** [BrunoReX/jmkvpropedit#15]
Sorry. New to this. How do i compile the src into .EXE?

TQ

**Comment by Bben01** [comment]
Just don't. Download the .zip folder and the .exe is inside it

**Comment by Gillous** [comment]
Hi!

Go look for it in: https://github.com/BrunoReX/jmkvpropedit/releases

cheers

**Comment by BrunoReX** [comment]
Very late, but you need to download both a JDK and Apache Ant, have both in your path, open a command prompt to the source dir and type "ant jar" or "ant exe".
