### ISSUE TITLE
Where is the jmkvproedit.jar file?

### ISSUE THREAD

**Issue by MigXIX** [BrunoReX/jmkvpropedit#17]
Hi, where can I find jmkvproedit.jar files? I only see this file
\jmkvpropedit-1.4.3\src\io\github\brunorex\jmkvproedit.java

Launch4j.exe won't let me compile the file.

Thanks for the help.
I am not a programmer.

**Comment by Gillous** [comment]
Hi!

you can have it here:
https://github.com/BrunoReX/jmkvpropedit/releases

Best wishes!

Gilles
