### ISSUE TITLE
File processing doesn't start

### ISSUE THREAD

**Issue by sebfrie** [BrunoReX/jmkvpropedit#2]
Hey there,
using version 1.3.3.1 aswell as 1.3.4pre, the program sometimes just doesn't do anything when clicking "process files" (Windows 8.1 64bit, Java 8 Update 31). Occasionally, it does work and the results are as expected.
Is there anything I should account for? Is this a known problem?

**Comment by BrunoReX** [comment]
Should be fixed in v1.4 if not open another issue.
