### ISSUE TITLE
Suddenly Stopped Working: Shows Command Line and Then Opens New Window

### ISSUE THREAD

**Issue by NotMyMainOne** [BrunoReX/jmkvpropedit#20]
As the title says, after working great for the past year, the program suddenly stopped working and I can't figure out what I could have done to make it stop working. I didn't change any program settings or anything like that. What happens is I select my normal options and then when I click to process the changes, it shows the command line code and then opens two new jmkvpropedit instances that are blank while not making any changes. I've tried re-downloading it and making sure nothing changed and I'm at a loss.

**Comment by brymerr921** [comment]
I just tested out version 1.4.3, and got it to work. I double-clicked JMkvpropedit.jar to run it, and under the "General" tab I changed the path of "Mkvpropedit executable" to "C:\Program Files\MKVToolNix\mkvpropedit.exe", which was installed with MKVToolNix.
