### ISSUE TITLE
"This application requires a Java Runtime Environment 1.7.0"

### ISSUE THREAD

**Issue by elisimpson** [BrunoReX/jmkvpropedit#25]
I'm using a newer open Java JRE from https://adoptopenjdk.net/

Any way this app can be made compatible?

**Comment by elisimpson** [comment]
It will launch if using the JAR or BAT, but the EXE gives the error about requiring at least Java 8. I'm using a much newer version. Maybe the EXE is failing because it's looking for an typical windows install instead of the JAVA_HOME path? It'd be nice to have the EXE work, but if you can't fix it no big deal, as there is a workarorund.

**Comment by BrunoReX** [comment]
> It will launch if using the JAR or BAT, but the EXE gives the error about requiring at least Java 8. I'm using a much newer version. Maybe the EXE is failing because it's looking for an typical windows install instead of the JAVA_HOME path? It'd be nice to have the EXE work, but if you can't fix it no big deal, as there is a workarorund.

adoptopenjdk.net has been replaced with adoptium.net.
When running the installer check "JavaSoft (Oracle) registry keys" to make sure the Launch4j executable can find it.

Edit: I've released a new version that tries to work around this issue too.
