### ISSUE TITLE
Completely removing Title Parameter

### ISSUE THREAD

**Issue by AlexSargon** [BrunoReX/jmkvpropedit#3]
Greetings!

Your program is very simple to use, and I love that I will be able to edit mkv's en masse.

I have mkv files, however that have the name of the person that made them available set as the Title, so if I add a number of episodes to my VLC player, I have no way to sort them so I can watch them in order. They all are called "name of show - Pahe,in" or something to that effect.

I either need to each file's Title to match the file name, or remove the Title parameter completely. If I leave the Title parameter blank, then VLC displays nothing, rather than the actual file name,

Please let me know if there is a string I can enter into the TItle box that will disable the parameter and allow VLC to show the name of the file.

Thank you for this useful tool, and I hope you are able to explain how to make it even more useful. :)

**Comment by BrunoReX** [comment]
This seems to be the behavior with the current MKVToolnix version if you leave the title empty.

**Comment by Wakakug** [comment]
Even though this is closed, might still be of help. Right now I am using JMkvpropedit 1.4.3, MKVToolNix 29.0, and JRE 10.0.1 combination.

To remove the Title header tag, in JMkvpropedit, go to General tab, then below check the Extra Parameters checkbox, then put

--edit info --set title=

into the input box, then click Process Files button at the bottom.
