### ISSUE TITLE
Java Error with v1.5

### ISSUE THREAD

**Issue by ImFilippo** [BrunoReX/jmkvpropedit#30]
Hi, i've downloaded the new version but i got this error:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/3F5Bpfb/img.png" alt="img" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/wBD6TkK/img2.png" alt="img2" border="0"></a>

I have the latest version of java installed on windows 10 so I don't understand why (the previous version 1.4.3 works fine).
Thank you!

**Comment by BrunoReX** [comment]
Which version do you have, like where did you download it from? I could try looking into this.
I used the latest from here https://adoptium.net/ and it worked fine
Did you try launching from the JAR instar of the EXE?

**Comment by ImFilippo** [comment]
> Which version do you have, like where did you download it from? I could try looking into this. I used the latest from here https://adoptium.net/ and it worked fine Did you try launching from the JAR instead of the EXE?

I have this [version](https://community.chocolatey.org/packages/jre8), installed from chocolatey.

**Comment by BrunoReX** [comment]
I see if I can make Java 8 the minimum version and update the release, but I'd advise to using a newer version anyway.

**Comment by BrunoReX** [comment]
Try v1.5.1 and see if you still have issues running it.
