### ISSUE TITLE
JMKVpropedit not working since MKVToolnix v20

### ISSUE THREAD

**Issue by PJThys** [BrunoReX/jmkvpropedit#5]
JMKVpropedit seems still to be using deprecated features that have been removed in release 20 (https://www.bunkus.org/blog/2018/01/mkvtoolnix-v20-0-0-released/). 
Not a bug in MKVToolNix. Ask the JMKVpropedit authors to update their software.

**Comment by BrunoReX** [comment]
Should be fixed in v1.4 if not open another issue.
