### ISSUE TITLE
Unable to select folders

### ISSUE THREAD

**Issue by sbach89** [BrunoReX/jmkvpropedit#6]
File structure is Movies\[movie]\[movie].mkv

In order to do batch, I have to go through each folder and add the movie individually. Any way to add a folder and the subfolders?

**Comment by BrunoReX** [comment]
You add a folder you want to add every MKV inside of that folder and its subfolders (recursively)? That's how it currently works (or should work, at least).

You just have to drag and drop, but I may add a button for it, I forgot why I didn't add one.

**Comment by sbach89** [comment]
Yes for some reason when I try to drag and drop it didn't allow it, and when I try to add folders, I select all, and it just unselects them and doesn't add them.

**Comment by sbach89** [comment]
So I just tried dragging and dropping again and it worked! Not sure if it was because I used the exe or the jar before, but it's good now.

Thanks!

**Comment by sbach89** [comment]
Actually it was a permissions issue with running as admin. If I elevate to run as admin, it doesn't allow dragging and dropping. I just modified my user account to have permissions to modify the files.

**Comment by BrunoReX** [comment]
Yeah running explorer as admin will cause issues with any application running with regular permissions as far as I know (or vice versa).
I added a button in release v1.4.3, by the way!
