### ISSUE TITLE
Error: This file could not be opened or parsed

### ISSUE THREAD

**Issue by InsaneDuck** [BrunoReX/jmkvpropedit#7]
it's showing "Error: This file could not be opened or parsed" but the file is not opened in any other program i tried rebooting system just to make sure it is not being used by some other program still shows this error worked for some mkv files (using JMkvpropedit 1.4.3,mkvtoolnix v23.0.0,java 8 update 171)

**Comment by szdavid5** [comment]
Hey! Im experiencing the same problem. How did you fix this?
